# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Álvaro Luque Vargas
title: Full stack - Software engineer
email: alvaro_25_98@hotmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  cuardiper
# stackoverflow_username: "00000001"
# instagram_username: alv.luque
linkedin_username: álvaro-luque-vargas-032a27167
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  **Full stack developer** with 3+ years of experience, from Barcelona, Spain. Recent graduate of a master's **degree in blockchain technologies**.

  I'am currently **focused** on **blockchain** and **web3** projects and I'am looking for a position to keep growing on that area. In October 2022, my team and I **participated** in the **ETHBogota hackathon**, where we won several prizes.

  I have experience on **multiple developing areas**, like UX design, front-end and back-end development, cloud services…All this different kind of tasks gave me a **good vision about all the proccesses** involved in software development.

  ## **My best practices**
  * I love writing **self descriptive code** that don't need a lot of documentation.
  * **Refactoring** iterations to improve code quality.
  * **Code review** to ensure code quality and learn from other developers.




content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Olympus Project
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Blockchain platform to play and win on competitive games tournaments, leagues, etc. Building a whole community around the gaming industry ecosystem.
        description: | # this will include new lines to allow paragraphs
          The idea for this project comes from the working group of the master in blockchain technologies. We developed the idea in the ETHBogota hackathon organized by ETHGlobal where we won several awards. 
          I used this project to improve many of my skills and learn a lot about web3 development. We keep developing and learning! <mark>React</mark>/<mark>NextJS</mark> <mark>Tailwind</mark> <mark>ethers.js</mark> <mark>wagmi.sh</mark> <mark>Solidity</mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: M. Moleiro Editor
        link: www.moleiro.com
        # link_text: boringcompany.com
        sub_title: Full Stack Developer
        caption: June 2019 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            * Designed new UI to improve usability and UX.
            * Analyse and optimise bottlenecks on various internal tools, thereby improving productivity.
            * Exhaustive refactoring of the CRM software (legacy code) to improve performance and code quality.
            * Designed and devoloped an internal tool to manage shipments and keep tracking of deliveries.
            * Oversaw the development of a junior programmer's project.
            * Worked on website page speed and SEO optimizations.

            <mark>PHP</mark>/<mark>Symfony</mark> <mark>MySQL</mark> <mark>Bootstrap</mark> <mark>JavaScript</mark> <mark>AWS</mark> <mark>jQuery</mark>

      - layout: left
        title: CBP Group
        link: www.cbp.fr/en/
        # link_text: boringcompany.com
        sub_title: IT QUALITY ASSURANCE
        caption: Agoust 2018 - February 2019
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Quality assurance and testing of the different tools used by the operations team.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UPC School
        caption: 2021 - October 2022
        sub_title:  Master's degree in Blockchain Technologies
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Graduated in a master's in Blockchain Technologies. Truly motivated by the changes and new opportunities that this technology brings us, this is where I want to devote my professional life.

      - layout: left
        title: Universitat Politecnica de Catalunya
        caption: 2016 - 2020
        sub_title: COMPUTER ENGINEERING
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Studied computer engineering at the UPC, the best tech school in Catalonia specialized in software engineering.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-cayman