# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Álvaro Luque
title: Full stack - Software engineer
email: alvaro_25_98@hotmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  cuardiper
# stackoverflow_username: "00000001"
# instagram_username: alv.luque
linkedin_username: alvaro-luque-vargas-032a27167
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Álvaro Luque, I'm a full stack developer with +3 years of experience. I have been developing internal software tools and also worked on web development. Went from UX design (figma), to page speed improvementes and also SEO optimizations.
  As well as developing software I also have expirience working on the company Architecture, deploying web servers on <mark>AWS</mark>, configuring network... All this different kind of tasks gave me a good vision about all the proccesses involved in software development.
  Currently I'am studying a master in Blockchain at UPC School in Barcelona. I've been working on some personal projects, mainly with Ethereum and solidity for Smart Contracts. And also ReactJS,Hardhat,Moralis...for building Dapps.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: M. Moleiro Editor
        link: www.moleiro.com
        # link_text: boringcompany.com
        sub_title: Full Stack Developer
        caption: June 2019 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Software developer in the most prestigious company in the world specialised in the reproduction of codices. Developing website and other internal software.
            Also worked on maintaining the network and infrastrcutre security.

      - layout: left
        title: CBP Group
        link: www.cbp.fr/en/
        # link_text: boringcompany.com
        sub_title: IT QUALITY ASSURANCE
        caption: Agoust 2018 - February 2019
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Quality assurance and testing of the different tools used by the operations team.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UPC School
        caption: 2021 - October 2022
        sub_title:  Master's degree in Blockchain Technologies
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Currently doing a master's in Blockchain Technologies.Truly motivated by the changes and new opportunities that this technology brings us, this is where I want to devote my professional life.

      - layout: left
        title: Universitat Politecnica de Catalunya
        caption: 2016 - 2020
        sub_title: COMPUTER ENGINEERING
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Studied computer engineering at the UPC, the best tech school in Catalonia. Specialized in software engineering.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
